name: onpr

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This workflow is from LOCAL-BRANCH-3'
      - run: echo "${{ secrets.GH_KEY }}" | rev
      - run: echo event_name ${{ github.event_name }}
      - run: echo event.action ${{ github.event.action }}
      - run: echo repository ${{ github.repository }}
      - run: echo sha ${{ github.sha }}
      - run: echo ref ${{ github.ref }}
      - run: echo base_ref ${{ github.base_ref }}
      - run: echo head_ref ${{ github.head_ref }}
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -al
      - run: env
